
DROP TABLE IF EXISTS rating_MPA, genre, films, users, films_genres, likes, friends_list;

CREATE TABLE IF NOT EXISTS rating_MPA (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(5)
);

CREATE TABLE IF NOT EXISTS genre (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(30)
);

CREATE TABLE IF NOT EXISTS films (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar NOT NULL,
    description varchar(200),
    releaseDate date,
    duration int,
    ratingMPA_id int REFERENCES rating_MPA (id)
);

CREATE TABLE IF NOT EXISTS users (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email varchar NOT NULL,
    login varchar NOT NULL,
    name varchar,
    birthday date
);

CREATE TABLE IF NOT EXISTS films_genres (
    film_id int REFERENCES films (id),
    genre_id int REFERENCES genre (id)
);

CREATE TABLE IF NOT EXISTS likes (
    film_id int REFERENCES films (id),
    user_id int REFERENCES users (id)
);

CREATE TABLE IF NOT EXISTS friends_list (
    user_id int REFERENCES users (id),
    friend_id int REFERENCES users (id),
    is_friend boolean
);